services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./backing-services/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./backing-services/datasources.yml:/etc/grafana/provisioning/datasources.yml
    networks:
      - localprom
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - localprom

networks:
  localprom:
    driver: bridge
